apiVersion: v2
name: sygna-hub-helm
description: A Helm chart for deploying Sygna Hub backend and frontend for local and AWS EKS environments.
type: application
version: 0.0.6
appVersion: "latest-beta"