apiVersion: v1
kind: Service
metadata:
  name: {{ include "sygna-hub.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "sygna-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sygna-hub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.frontend.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sygna-hub.fullname" . }}-{{ .Values.backend.name }}
  labels:
    {{- include "sygna-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sygna-hub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}